### Task -16 Break ,Continous ,Pass

In [1]:
av = 7
x = int(input("How Many Candies Do you Want"))

i  = 1
while i <= x:
    
    if i>av:
        Print("Out Of Stock")
        break
    
    print("candy")
    i=+1

        
print("Bye")

How Many Candies Do you Want2
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
candy
cand

KeyboardInterrupt: 

In [2]:
## Divisible by 3
for i in range(1,21):
    
    if i %3==0:
        continue
    print(i)
print("Bye") 

1
2
4
5
7
8
10
11
13
14
16
17
19
20
Bye


In [3]:
# Divisible by 3 or 5 
for i in range(1,21):
    
    if i%3==0 or i%5==0:
        continue
        
    print(i)
    
print("Bye")    
        


1
2
4
7
8
11
13
14
16
17
19
Bye


In [4]:
## Only Divisible by 15
for i in range(1,21):
    
    if i%3==0 and i%5==0:
        continue
        
    print(i)
    
print("Bye")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
Bye


In [5]:
for i in range(1,21):
    
    if i%2==0:
        pass
    else:
        print(i)
            
print("Bye")            
            
            

1
3
5
7
9
11
13
15
17
19
Bye


### Task 17 -Printing Patterns in Python 

In [6]:
print("# ",end =" ")
print("# ",end =" ")
print("# ",end =" ")
print("# ",end =" ")

#  #  #  #  

In [7]:
for j in range(4):
    print("#",end=" ")

# # # # 

In [8]:
for i in range(4):  ## Giving the i loop to j block and name it 
    for j in range(4):
        print("#",end="")
    print()

####
####
####
####


In [9]:
for i in range(4):
    for j in range(i+1):
        print("#",end="")
    print()
        

#
##
###
####


In [10]:
for i in range(4):
    for j in range(4-i):
        print("#",end="")
        
    print()

####
###
##
#


In [11]:
for i in range(4):
    for j in range(4-i):
        print("$",end="")
        
    print()

$$$$
$$$
$$
$


###  Task -18 FOR and ELSE Together 

In [12]:
nums = [12,13,16,17,18,26,29]

for num in nums:
    if num%5 == 0:
        print(num)
        break
else:
    print('No Number to print')    

No Number to print


In [13]:

nums = [12,15,16,175,18,25,29]

for num in nums:
    if num%5 == 0:
        print(num)
        
else:
    print('No Number to print')

15
175
25
No Number to print


### Task 19 Various types of pycode of  Prime Or Not 

In [14]:
num  = 7 
for i in range(2,num):
    if num %1 == 0:
        print("Not Prime")
    else:
        print("Prime Number")    

Not Prime
Not Prime
Not Prime
Not Prime
Not Prime


In [15]:
num  = 7 
for i in range(2,num):
    if num %1 == 0:
        print("Not Prime")
        break   
else:
    print("Prime Number") 

Not Prime


In [20]:
# Printing upto 50 primes
for num in range(1,50):
    for i in range(2,num):
        if num%i==0:
            break
    else:
        print(num)

1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [21]:
num = 15
  
# If given number is greater than 1 
if num > 1: 
      
   # Iterate from 2 to n / 2  
   for i in range(2, num//2): 
         
       # If num is divisible by any number between  
       # 2 and n / 2, it is not prime  
       if (num % i) == 0: 
           print(num, "is not a prime number") 
           break
   else: 
       print(num, "is a prime number") 
  
else: 
   print(num, "is not a prime number")

15 is not a prime number


In [22]:
for i in range(2,(num//2)+1):
       if (num % i) == 0: 
           print(num, "is not a prime number") 
           break
else: 
       print(num, "is a prime number")

15 is not a prime number


In [23]:
def prime(num):
    for i in range(2,num):
        if num % i == 0:
            return "not a prime number"
    else:
        return "prime number"
num = int(input("enter a number: "))
print(prime(num))

enter a number: 


ValueError: invalid literal for int() with base 10: ''

In [24]:
# Asking the user for input
numb = int(input('Enter a number: '))

# Loop statement
for i in range(numb):
    if numb % 2 == 0:
        print('Not prime')
        break
else:
    print('Prime')

Enter a number: 2
Not prime


In [25]:
x = int(input("enter a number"))

i=3
while 1<i:
    if x%i==0:
        print("number is not a prime number")
        break
    i=i-1
else:
    print("It is a prime number")

enter a number4
number is not a prime number


In [27]:
a=int(input('Enter number:'))
check = False
for i in range (2,a):
    if a%i == 0:
        print('its not a prime number')
        check = True
        break
if check ==  False:
    print('Its a prime number')

Enter number:7
Its a prime number


In [28]:
values=int(input ("enter the values"))
for i in range(2,values):
     if(values%i==values):
            print(" not prime")
            break
else:
    print (" it's  prime number")


enter the values9
 it's  prime number


### Task 20 Arrays 

* We have same type in the Array{int,float
* First We Have to specify the TYPE and Second one to be the VALUES
* 

In [29]:
from array import *

vals = array('i',[5,-9,8,0,2]) # small i for +ve & -ve values
print(vals.buffer_info())

(1398817085720, 5)


In [30]:
from array import *  

vals = array('I',[5,9,8,0,2])  # capital i only for +values
print(vals.buffer_info())  # Address and size
print(vals.reverse)
print(vals[0])

(1398817085768, 5)
<built-in method reverse of array.array object at 0x00000145AFF8E2F0>
5


In [31]:
vals = array('i',[5,-9,8,0,2])

for i in range(5):
    print(vals[i])

5
-9
8
0
2


In [32]:
vals = array('i',[5,-9,8,0,2])
for e in vals:
    print(e)

5
-9
8
0
2


In [33]:
## Adding New Array
vals = array('i',[5,9,8,0,2])

newArr = array(vals.typecode,(a for a in vals))

for e in newArr:
    print(e)
    
    

5
9
8
0
2


In [34]:
# if we to make square of the number in vals 

vals = array('i',[5,9,8,0,2])

newArr = array(vals.typecode,(a*a for a in vals))

for e in newArr:
    print(e)

25
81
64
0
4


In [35]:
from array import *
vals = array('d',[4,3,1,12])
vals=sorted(vals)


print(vals)

[1.0, 3.0, 4.0, 12.0]


In [36]:
from array import *
vals = array('u',['a','c','i','o'])
  
for e in vals:
    print(e)

a
c
i
o


#### Task -  21 Array values from User in Python Search in Array

In [50]:
##  i want to search for the value tell me the index number 

from array import  *

arr = array('i',[])

n = int(input("Enter the length of the array"))

for i in range(n):
        x = int(input("Enter the next value"))
        arr.append(x)
        
        
print(arr)


val = int(input("Enter the value for search"))

k = 0
for e in arr:
    if e==val:
        print(k)
        break
    k+=1    
print(arr.index(val)) ##  we can use a function by index

Enter the length of the array3
Enter the next value4
Enter the next value5
Enter the next value6
array('i', [4, 5, 6])
Enter the value for search5
1
1


In [39]:
import array as a
arr=a.array("i",[])
lent=int(input("Enter the length of array : "))
for i in range(lent):
    val=int(input("Enter the elements of array one by one and press enter"))
    arr.append(val)
print(arr)
arr2=a.array('i',[])
del_elm=int(input("Enter the element you wish to remove/delete : "))
for element in arr:
    if del_elm==element:
        continue
    else:
        arr2.append(element)

print("The new array is : \n",arr2)

Enter the length of array : 1
Enter the elements of array one by one and press enter2
array('i', [2])
Enter the element you wish to remove/delete : 3
The new array is : 
 array('i', [2])


In [47]:
from array import *
arr=array('i',[])
n=int(input("enter the length of the array="))
for i in range(n):
       x=int(input ("enter the next value="))
       arr.append(x)
print(arr)
for e in range(n):
         if(e==2):
            pass
         else:
            print(arr[e])

enter the length of the array=2
enter the next value=3
enter the next value=5
array('i', [3, 5])
3
5


#### Task - 22 Ways of Creating Arrays in Numpy
* Single Dimensional 
* Multiple Dimensional (matrix )
* Copying an Array in Python in 6 ways .
* ARRAY , LINSPACE , LONGSPACE , ARANGE , ZEROS ,ONES

In [69]:
arr1 = array([1,2,3,4,5])
arr2 = array([6,1,9,3,2])

arr = arr1 + arr2
print(arr)



arr1 = array([1,2,3,4,5])
print(sin(arr1))


arr1 = array([1,2,3,4,5])
print(cos(arr1))


[ 7  3 12  7  7]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [57]:
from numpy import *
arr = array([7,5,8,2,3,4],int)
print(arr.dtype)
print(arr)

arr = linspace(0,15)
arr = arange(1,15,2)

arr = logspace(1,40,5)
print('%.2f' %arr[4])

arr = ones(5,int)
print(arr)

int32
[7 5 8 2 3 4]
10000000000000000303786028427003666890752.00
[1 1 1 1 1]


In [64]:
arr = array([2,3,4,5,6,7.0]) ## if it seen an float type in int type value it will automate to float
print(arr.dtype)
print(arr)
arr1 = array([2,3,4,5,6,7,float])
print(arr1)

float64
[2. 3. 4. 5. 6. 7.]
[2 3 4 5 6 7 <class 'float'>]


In [67]:
arr = linspace(0,16,10) ## Why only float value is we r dividing into equal legth 
print(arr)
arr =arange(1,16,8)
print(arr)

[ 0.          1.77777778  3.55555556  5.33333333  7.11111111  8.88888889
 10.66666667 12.44444444 14.22222222 16.        ]
[1 9]


In [72]:
arr = logspace(0,16,10) 
print(arr)
arr =arange(1,16,8)
print(arr)

[1.00000000e+00 5.99484250e+01 3.59381366e+03 2.15443469e+05
 1.29154967e+07 7.74263683e+08 4.64158883e+10 2.78255940e+12
 1.66810054e+14 1.00000000e+16]
[1 9]


In [73]:
arr = logspace(1,40,5)
print('%.2f' %arr[4])

arr = ones(5,int)
print(arr)

10000000000000000303786028427003666890752.00
[1 1 1 1 1]


In [76]:
arr = zeros(5,int)
print(arr)
arr = zeros(5)
print(arr)

[0 0 0 0 0]
[0. 0. 0. 0. 0.]


### Task - 23 Copying an Array in Python

In [87]:
from numpy import *

arr1 = array([1,2,3,4,5]) # Vectorized Operation 
arr2 = array([6,1,9,3,2])
arr = arr1 + arr2
print(arr)



arr1 = array([1,2,3,4,5]) # Trigoometery operation
print(sin(arr1))


arr1 = array([1,2,3,4,5])
print(cos(arr1))


arr1 = array([1,2,3,4,5])
print(log(arr1))


arr1 = array([1,2,3,4,5])
print(sqrt(arr1))


arr1 = array([1,2,3,4,5])
print(sum(arr1))


arr1 = array([1,2,3,4,5])
print(min(arr1))


arr1 = array([1,2,3,4,5])
print(max(arr1))


arr1 = array([1,2,3,4,5])
arr2 = array([6,1,9,3,2])
print(concatenate([arr1,arr2]))


arr1 = array([2,6,8,1,3])
arr2 = arr1  # Aliasing 

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))


arr1 = array([2,6,8,1,3])
arr2 = arr1.view() # Shallow Copying
arr2 = arr1.copy() # Deep Copying

arr1[1] = 7

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[ 7  3 12  7  7]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
1
5
[1 2 3 4 5 6 1 9 3 2]
[2 6 8 1 3]
[2 6 8 1 3]
1398960784928
1398960784928
[2 7 8 1 3]
[2 6 8 1 3]
1398950221424
1398960784928


### Task - 25 Working with Matrix in Python

In [102]:
arri = array([
           
               [1,2,3], 
               [4,5,6],
             ])

print(arr1)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.flatten())

# Creating 3 dimensional value 

arri1 = array([
           
               [1,2,3,7,9,11], 
               [4,5,6,13,14,22],
             ])
arri2 = arri1.flatten() 
arri3 =arri2.reshape(2,2,3)
print(arri3)

[2 7 8 1 3]
1
(5,)
5
[ 7  3 12  7  7]
[[[ 1  2  3]
  [ 7  9 11]]

 [[ 4  5  6]
  [13 14 22]]]


In [112]:
m = matrix(arri1)
print(m)
m1 = matrix('1 2 3; 6 4 5;1 6 7')
print(diagonal(m1))
print(m1.min())
print(m1.max())

m2 = matrix('1 2 3; 6 4 5;1 6 7')
m3 = matrix('1 2 3; 6 8 5;2 6 7')

m4 = m2 + m3;
m5 = m2 * m3;
print(m4)
print(m5)

[[ 1  2  3  7  9 11]
 [ 4  5  6 13 14 22]]
[1 4 7]
1
7
[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]
[[19 36 34]
 [40 74 73]
 [51 92 82]]


### TASK -26 Functions in Python.......................(Defining ,Calling) 
*   Function Arguments in Python
*  When you have a complex project you may make split into  samll tasks 




In [114]:
def greet():
    print("hello")
    print("Good Morning")

greet()

hello
Good Morning


In [115]:
def add(x,y):
    c = x+y
    print(c)
    
add(754,567)

1321


In [118]:
def add(x,y):
    c = x+y
    return c

result = add(757,767)


In [120]:
def add_sub(x,y):
    c = x+y
    d = x-y
    return c,d

result1,result2 =add_sub(757,767)
print(result1,result2)

1524 -10


In [121]:
def update(x):
    x =7
    print(x)
    
a = 10
update(a)
print(a)

7
10


In [126]:
## PASS BY VALE(only) \ PASS BY REFERENCE (address)  CONCEPT

def update(x):
    x =7
    print("x", x)
    
a = 15
update(a)
print("a",a)

x 7
a 15


In [133]:
def update(lst):
    
    print(id(lst))

    lst[1] = 25
    print(id(lst))
    print("x ", lst)

In [134]:
lst = [10,20,30]
print(id(lst))
update(lst)
print("lst ", lst)

1398976935112
1398976935112
1398976935112
x  [10, 25, 30]
lst  [10, 25, 30]


In [137]:
def add(x,y):   # Formal Arguments 
    c = x+y
    print(c)
    
add(22,22)

44


###  Types of Actual Arguments 

* Position
* keyword
* Default
* Variable


In [ ]:
def person(name , age):   # Formual Arguments
    print(name)
    print(age)

person(age=27,name='manohar')

In [140]:
def person(name , age=18):
    print(name)
    print(age)

person('manohar',28) # Passing 

manohar
28


In [147]:
def sum(a,b):
    c = a+b
    print(c)
    
sum(35,45)

80


In [150]:
def sum(a,*b):
    c = a
    
    for i in b:
        c = c+i
    print(c)
    
sum(35,456)

491


In [153]:
def sum(a,*b):
    c = 0
    
    for i in b:
        c = c+i
    print(c)
    
sum(35,456)

456


In [148]:
def sum(*b):   # it have multiple values
    c = 0
    for i in b:
        c = c + i
        print(c)
sum(5,6,34,78)

5
11
45
123


### Task 27 keyword variable length Argument 

In [ ]:
def person(name, **data):
    print(name)
    print(data)
person('manohar',age=28,city='guntur',mob=9705561871)

In [158]:
def person(name, **data):
    print(name)
    for i,j in data.items():
        print(i,j)
person('manohar',age=28,city='hyderabad',mob=9705561871)

manohar
age 28
city hyderabad
mob 9705561871
